import os

import streamlit as st
from groq import Groq

MODEL_ID = "llama-3.1-8b-instant"
MAX_NEW_TOKENS = int(os.getenv("MAX_NEW_TOKENS", "512"))
SYSTEM_PROMPT = os.getenv(
    "SYSTEM_PROMPT",
    "You are Sangram's Tantra, a helpful, clear, and practical AI assistant. "
    "Answer honestly, explain difficult ideas simply, and say when you are uncertain.",
)

st.set_page_config(page_title="Sangram's Tantra", page_icon="✦", layout="centered")


def get_groq_key() -> str:
    key = os.getenv("GROQ_API_KEY", "")
    if key:
        return key
    try:
        return str(st.secrets.get("GROQ_API_KEY", ""))
    except Exception:
        return ""


@st.cache_resource(show_spinner=False)
def get_client(api_key: str):
    return Groq(api_key=api_key)


def generate_answer(message: str, history: list[dict[str, str]]) -> str:
    api_key = get_groq_key()
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is missing. Add it in Streamlit: Manage app → Settings → Secrets."
        )

    client = get_client(api_key)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.extend(history)
    messages.append({"role": "user", "content": message})

    response = client.chat.completions.create(
        messages=messages,
        model=MODEL_ID,
        max_tokens=MAX_NEW_TOKENS,
        temperature=0.7,
        top_p=0.9,
    )
    return response.choices[0].message.content.strip()


st.title("Sangram's Tantra")
st.caption("Your personal AI assistant, powered by Llama 3.1 through Groq")
st.info("Responses are generated by a fast hosted model, so your computer does not run the AI.", icon="⚡")

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask Sangram's Tantra anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    history = st.session_state.messages[:-1]
    with st.chat_message("assistant"):
        with st.spinner("Sangram's Tantra is thinking..."):
            try:
                response = generate_answer(prompt, history)
                st.markdown(response)
            except Exception as exc:
                response = "I could not reach the hosted model. Please check the Groq secret and app logs."
                st.error(f"{response}\n\nTechnical details: {exc}")

    st.session_state.messages.append({"role": "assistant", "content": response})

with st.sidebar:
    st.header("About")
    st.write("Sangram's Tantra uses Groq-hosted Llama 3.1 inference.")
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()
