import os

import streamlit as st
from huggingface_hub import InferenceClient

MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
MAX_NEW_TOKENS = int(os.getenv("MAX_NEW_TOKENS", "256"))
SYSTEM_PROMPT = os.getenv(
    "SYSTEM_PROMPT",
    "You are Sangram's Tantra, a helpful, clear, and practical AI assistant. "
    "Answer honestly, explain difficult ideas simply, and say when you are uncertain.",
)

st.set_page_config(page_title="Sangram's Tantra", page_icon="✦", layout="centered")


def get_hf_token() -> str:
    token = os.getenv("HF_TOKEN", "")
    if token:
        return token
    try:
        return str(st.secrets.get("HF_TOKEN", ""))
    except Exception:
        return ""


@st.cache_resource(show_spinner=False)
def get_client(token: str):
    return InferenceClient(model=MODEL_ID, token=token, provider="featherless-ai")


def generate_answer(message: str, history: list[dict[str, str]]) -> str:
    token = get_hf_token()
    if not token:
        raise RuntimeError(
            "HF_TOKEN is missing. Add it in Streamlit: Manage app → Settings → Secrets."
        )

    client = get_client(token)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.extend(history)
    messages.append({"role": "user", "content": message})

    response = client.chat_completion(
        messages=messages,
        max_tokens=MAX_NEW_TOKENS,
        temperature=0.7,
        top_p=0.8,
    )
    return response.choices[0].message.content.strip()


st.title("Sangram's Tantra")
st.caption("Your personal AI assistant, powered by Qwen2.5 through Hugging Face")
st.info("Responses are generated by a hosted model, so your computer does not run the AI.", icon="☁️")

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask Sangram's Tantra anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    history = st.session_state.messages[:-1]
    with st.chat_message("assistant"):
        with st.spinner("Sangram's Tantra is thinking..."):
            try:
                response = generate_answer(prompt, history)
                st.markdown(response)
            except Exception as exc:
                response = "I could not reach the hosted model. Please check the Streamlit Secrets and app logs."
                st.error(f"{response}\n\nTechnical details: {exc}")

    st.session_state.messages.append({"role": "assistant", "content": response})

with st.sidebar:
    st.header("About")
    st.write("Sangram's Tantra uses the Hugging Face Inference API.")
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()
