import os

import streamlit as st
from google import genai

MODEL_ID = "gemini-2.5-flash-lite"
MAX_OUTPUT_TOKENS = int(os.getenv("MAX_OUTPUT_TOKENS", "512"))
SYSTEM_PROMPT = os.getenv(
    "SYSTEM_PROMPT",
    "You are Sangram's Tantra, a helpful, clear, and practical AI assistant. "
    "Answer honestly, explain difficult ideas simply, and say when you are uncertain.",
)

st.set_page_config(page_title="Sangram's Tantra", page_icon="✦", layout="centered")


def get_gemini_key() -> str:
    key = os.getenv("GEMINI_API_KEY", "")
    if key:
        return key
    try:
        return str(st.secrets.get("GEMINI_API_KEY", ""))
    except Exception:
        return ""


@st.cache_resource(show_spinner=False)
def get_client(api_key: str):
    return genai.Client(api_key=api_key)


def generate_answer(message: str, history: list[dict[str, str]]) -> str:
    api_key = get_gemini_key()
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY is missing. Add it in Streamlit: Manage app → Settings → Secrets."
        )

    transcript = f"System instructions:\n{SYSTEM_PROMPT}\n\n"
    for item in history:
        role = "User" if item["role"] == "user" else "Sangram's Tantra"
        transcript += f"{role}: {item['content']}\n\n"
    transcript += f"User: {message}\n\nSangram's Tantra:"

    client = get_client(api_key)
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=transcript,
        config={"max_output_tokens": MAX_OUTPUT_TOKENS, "temperature": 0.7},
    )
    return response.text.strip()


st.title("Sangram's Tantra")
st.caption("Your personal AI assistant, powered by Gemini through Google AI Studio")
st.info("Responses are generated by a fast hosted model, so your computer does not run the AI.", icon="⚡")

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask Sangram's Tantra anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    history = st.session_state.messages[:-1]
    with st.chat_message("assistant"):
        with st.spinner("Sangram's Tantra is thinking..."):
            try:
                response = generate_answer(prompt, history)
                st.markdown(response)
            except Exception as exc:
                response = "I could not reach Gemini. Please check the Gemini secret and app logs."
                st.error(f"{response}\n\nTechnical details: {exc}")

    st.session_state.messages.append({"role": "assistant", "content": response})

with st.sidebar:
    st.header("About")
    st.write("Sangram's Tantra uses Gemini Flash-Lite through Google AI Studio.")
    if st.button("Clear conversation"):
        st.session_state.messages = []
        st.rerun()
